// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGwwmytzCNCc0SLssHrMapn0PNr6LBn2M',
    appId: '1:1045537127567:web:b1c27f25d0a0236c3fc4fa',
    messagingSenderId: '1045537127567',
    projectId: 'handjobs-notify',
    authDomain: 'handjobs-notify.firebaseapp.com',
    databaseURL: 'https://handjobs-notify-default-rtdb.firebaseio.com',
    storageBucket: 'handjobs-notify.appspot.com',
    measurementId: 'G-4V518GE008',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCXTW7mFvytEYaocCVcoYcIjQtg5eEzaY',
    appId: '1:1045537127567:android:5ff6d93c8a3e4ba73fc4fa',
    messagingSenderId: '1045537127567',
    projectId: 'handjobs-notify',
    databaseURL: 'https://handjobs-notify-default-rtdb.firebaseio.com',
    storageBucket: 'handjobs-notify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMdvQxXZR9RTME0PChY70XKZ9AT5CJaz8',
    appId: '1:1045537127567:ios:0c97a33d7cce73fa3fc4fa',
    messagingSenderId: '1045537127567',
    projectId: 'handjobs-notify',
    databaseURL: 'https://handjobs-notify-default-rtdb.firebaseio.com',
    storageBucket: 'handjobs-notify.appspot.com',
    iosClientId: '1045537127567-dju0buvq3vbst2udsb1k2bk25lov2snp.apps.googleusercontent.com',
    iosBundleId: 'com.handjobs.mobile.app',
  );
}
