const String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";
const String AUTH_REFRESH_KEY = "AUTH_REFRESH_KEY";
const String IS_FIRST_TIME_USER = "IS_FIRST_TIME_USER";

const String PROFESSION_TYPES = "PROFESSION_TYPES";

const String LOCATION_SUGGESTION_REQUEST = 'LOCATION_SUGGESTION_REQUEST';
